FAV-1 implemented basic functionality for Fhir-Avro conversion
Ferlab-Ste-Justine/fhavro pull request #1
Opened 2021-09-21 13:19 UTC by joelplourde3

First version of the Fhir <-> Avro converter (Fhavro), allow basic functionality for a limited number of resources (ex: Patient, Account, Appointment, etc):
- Convert from Fhir
- Convert from Avro

Known issues (Next step); 
- In Avro, Enum symbols need to conform to the same naming convention than Names. Therefore, it must starts with [A-Za-z_] and subsequent character must contain only [A-Za-z0-9_]. At the moment, some enum in FHIR contains illegal character (e.g. /, <, >, etc.).
- Extensions are not included in the schema and therefore are not serializable.
- Some resources contains cyclical definition therefore only 616 schemas are supported at the moment, some entities causes issues (only 43 out of 14348).

2021-09-22 14:06 UTC, celinepelletier requested changes
Some quick comments but overall very nice work ! 👏🏻 💯

2021-09-22 23:57 UTC, jecos approved these changes

2021-09-22 23:57 UTC, merged

2021-09-23 12:30 UTC, joelplourde3 commented on pom.xml
> +            <version>1.10.2</version>
Nope, was playing around with dependencies and forgot to rollback

2021-09-23 12:32 UTC, joelplourde3 commented on src/main/java/bio/ferlab/fhir/converter/exception/AvroConversionException.java
> +    public AvroConversionException(String message) {
Yeah we unfortunately do in Java, because I want to specify a custom message and otherwise the default constructor is (),

2021-09-23 12:36 UTC, joelplourde3 commented on src/main/java/bio/ferlab/fhir/schema/utils/JsonObjectUtils.java
> +            txt = txt.substring(0, 1).toLowerCase() + txt.substring(1);
Indeed, this was a quick fix to bypass a known issue, this section is/will be refactored in https://ferlab-crsj.atlassian.net/browse/FAV-3